'use client';

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { useTasks } from '@/hooks/use-tasks';
import { Badge } from '@/components/ui/badge';

export default function TasksPage() {
  const { tasks } = useTasks();

  const getBadgeVariant = (dueDate: string) => {
    const lowerCaseDate = dueDate.toLowerCase();
    if (lowerCaseDate.includes('today')) return 'destructive';
    if (lowerCaseDate.includes('tomorrow')) return 'secondary';
    return 'outline';
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold font-headline">Task Management</h1>
        <p className="text-muted-foreground">
          A list of tasks generated by the Assistant.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>All Tasks</CardTitle>
          <CardDescription>
            This is a prototype. Tasks are stored in memory and will be cleared on page refresh.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Person</TableHead>
                <TableHead>Task</TableHead>
                <TableHead>Due Date</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {tasks.length > 0 ? (
                tasks.map((task) => (
                  <TableRow key={task.id}>
                    <TableCell className="font-medium">{task.person}</TableCell>
                    <TableCell>{task.title}</TableCell>
                    <TableCell>
                      <Badge variant={getBadgeVariant(task.dueDate)}>
                        {task.dueDate}
                      </Badge>
                    </TableCell>
                  </TableRow>
                ))
              ) : (
                <TableRow>
                  <TableCell colSpan={3} className="h-24 text-center">
                    No tasks created yet. Try using the chatbot!
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
