
'use client';

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { useTasks } from '@/hooks/use-tasks';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Plus, Edit } from 'lucide-react';
import Modal from '@/components/ui/Modal';
import { CreateTaskModal } from '@/components/tasks/create-task-modal';
import { Task } from '@/hooks/use-tasks';
import { Tooltip, TooltipProvider, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';

export default function TasksPage() {
  const { tasks, addTask, updateTask } = useTasks();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingTask, setEditingTask] = useState<Task | null>(null);

  const getBadgeVariant = (dueDate: string) => {
    const lowerCaseDate = dueDate.toLowerCase();
    if (lowerCaseDate.includes('today')) return 'destructive';
    if (lowerCaseDate.includes('tomorrow')) return 'secondary';
    return 'outline';
  };

  const handleOpenCreateModal = () => {
    setEditingTask(null);
    setIsModalOpen(true);
  };
  
  const handleOpenEditModal = (task: Task) => {
    setEditingTask(task);
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setEditingTask(null);
  };

  const handleSaveTask = (task: Omit<Task, 'id'> & { id?: string }) => {
    if (task.id) {
        updateTask(task.id, task);
    } else {
        addTask({ ...task, id: `task-${Date.now()}` });
    }
    handleCloseModal();
  };

  return (
    <TooltipProvider>
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold font-headline">Task Management</h1>
          <p className="text-muted-foreground">
            A list of tasks generated by the Assistant or created manually.
          </p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>All Tasks</CardTitle>
            <CardDescription>
              This is a prototype. Tasks are stored in memory and will be cleared on page refresh.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Person</TableHead>
                  <TableHead>Task</TableHead>
                  <TableHead>Due</TableHead>
                  <TableHead>Description</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {tasks.length > 0 ? (
                  tasks.map((task) => (
                    <TableRow key={task.id}>
                      <TableCell className="font-medium">{task.person}</TableCell>
                      <TableCell>{task.task}</TableCell>
                      <TableCell>
                        <Badge variant={getBadgeVariant(task.dueDate)}>
                          {task.dueDate}
                        </Badge>
                      </TableCell>
                      <TableCell>{task.description || '—'}</TableCell>
                      <TableCell className="text-right">
                         <Tooltip>
                            <TooltipTrigger asChild>
                                <Button variant="ghost" size="icon" onClick={() => handleOpenEditModal(task)}>
                                    <Edit className="h-4 w-4" />
                                </Button>
                            </TooltipTrigger>
                            <TooltipContent>
                                <p>Edit Task</p>
                            </TooltipContent>
                        </Tooltip>
                      </TableCell>
                    </TableRow>
                  ))
                ) : (
                  <TableRow>
                    <TableCell colSpan={5} className="h-24 text-center">
                      No tasks created yet. Try the chatbot or the '+' button!
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>

      <Button
        className="fixed bottom-8 left-1/2 -translate-x-1/2 z-50 h-14 w-14 rounded-full shadow-lg"
        onClick={handleOpenCreateModal}
      >
        <Plus className="h-6 w-6" />
        <span className="sr-only">Create Task Manually</span>
      </Button>

      <Modal open={isModalOpen} onClose={handleCloseModal}>
        <CreateTaskModal
          task={editingTask}
          onClose={handleCloseModal}
          onSave={handleSaveTask}
        />
      </Modal>
    </TooltipProvider>
  );
}
