
'use client';

import { useState, useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { useTasks } from '@/hooks/use-tasks';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Plus, Edit } from 'lucide-react';
import Modal from '@/components/ui/Modal';
import { CreateTaskModal } from '@/components/tasks/create-task-modal';
import { Task, TaskStatus } from '@/hooks/use-tasks';
import { Tooltip, TooltipProvider, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { useCurrentUser } from '@/hooks/use-current-user';
import { useToast } from '@/hooks/use-toast';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { TASK_STATUSES } from '@/lib/constants';
import { format, parseISO, isPast } from 'date-fns';
import { cn } from '@/lib/utils';


export default function TasksPage() {
  const { hasPermission } = useCurrentUser();
  const { toast } = useToast();
  const { tasks, addTask, updateTask } = useTasks();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingTask, setEditingTask] = useState<Task | null>(null);

  const canView = hasPermission('TASK', 'view');
  const canCreate = hasPermission('TASK', 'create');
  const canUpdate = hasPermission('TASK', 'edit');

  const getStatusBadgeVariant = (status: string) => {
    const lowerCaseStatus = status.toLowerCase();
    if (lowerCaseStatus.includes('completed')) return 'default';
    if (lowerCaseStatus.includes('pending')) return 'destructive';
    if (lowerCaseStatus.includes('in progress')) return 'secondary';
    return 'outline';
  };

  const handleOpenCreateModal = () => {
    if (!canCreate) {
        toast({ title: 'Permission Denied', description: 'You do not have permission to create tasks.', variant: 'destructive' });
        return;
    }
    setEditingTask(null);
    setIsModalOpen(true);
  };
  
  const handleOpenEditModal = (task: Task) => {
    if (!canUpdate) {
        toast({ title: 'Permission Denied', description: 'You do not have permission to edit tasks.', variant: 'destructive' });
        return;
    }
    setEditingTask(task);
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setEditingTask(null);
  };

  const handleSaveTask = (task: Omit<Task, 'id' | 'createDate' | 'startDate' | 'completeDate' | 'status'> & { id?: string }) => {
    if (task.id) {
        updateTask(task.id, task);
    } else {
        addTask(task as Omit<Task, 'id' | 'createDate' | 'status'>);
    }
    handleCloseModal();
  };

  const handleStatusChange = (taskId: string, newStatus: TaskStatus) => {
    updateTask(taskId, { status: newStatus });
    toast({
        title: "Status Updated",
        description: `Task status changed to "${newStatus}".`
    });
  }

  const formatDate = (dateString?: string | null) => {
    if (!dateString) return '—';
    try {
      return format(parseISO(dateString), 'dd MMM yyyy');
    } catch {
      return dateString;
    }
  };

  const terminalStatuses: TaskStatus[] = ['Completed', 'Cancelled', 'Rejected'];

  if (!canView) {
      return (
          <Card>
              <CardHeader><CardTitle>Access Denied</CardTitle></CardHeader>
              <CardContent><p>You do not have permission to view this page.</p></CardContent>
          </Card>
      );
  }

  return (
    <TooltipProvider>
      <div className="space-y-6">
        <div>
          <h1 className="text-3xl font-bold font-headline">Task Management</h1>
          <p className="text-muted-foreground">
            A list of tasks generated by the Assistant or created manually.
          </p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>All Tasks</CardTitle>
            <CardDescription>
              This is a prototype. Tasks are stored in memory and will be cleared on page refresh.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Client</TableHead>
                  <TableHead>Category</TableHead>
                  <TableHead>RM</TableHead>
                  <TableHead>Create Date</TableHead>
                  <TableHead>Start Date</TableHead>
                  <TableHead>Due Date</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Description</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {tasks.length > 0 ? (
                  tasks.map((task) => {
                    const isOverdue = task.status === 'In Progress' && task.dueDate && isPast(parseISO(task.dueDate));
                    const isTerminal = terminalStatuses.includes(task.status);

                    return (
                        <TableRow key={task.id} className={cn(isOverdue && 'text-destructive')}>
                          <TableCell className="font-medium">{task.clientName}</TableCell>
                          <TableCell>{task.category}</TableCell>
                          <TableCell>{task.rmName}</TableCell>
                          <TableCell>
                            <Tooltip>
                                <TooltipTrigger>{formatDate(task.createDate)}</TooltipTrigger>
                                <TooltipContent>
                                    <p>Created: {task.createDate ? format(parseISO(task.createDate), 'PPpp') : 'N/A'}</p>
                                    {task.completeDate && <p>Completed: {format(parseISO(task.completeDate), 'PPpp')}</p>}
                                </TooltipContent>
                            </Tooltip>
                          </TableCell>
                          <TableCell>{formatDate(task.startDate)}</TableCell>
                          <TableCell>{formatDate(task.dueDate)}</TableCell>
                          <TableCell>
                             <DropdownMenu>
                                <DropdownMenuTrigger asChild disabled={!canUpdate || isTerminal}>
                                    <Badge 
                                        variant={getStatusBadgeVariant(task.status)}
                                        className={cn((canUpdate && !isTerminal) ? "cursor-pointer" : "cursor-not-allowed", isOverdue && 'border-destructive')}
                                    >
                                    {task.status}
                                    </Badge>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent>
                                    {task.status === 'Pending' && (
                                        <DropdownMenuItem onSelect={() => handleStatusChange(task.id, 'In Progress')}>
                                            Move to In Progress
                                        </DropdownMenuItem>
                                    )}
                                    {task.status === 'In Progress' && (
                                        <>
                                            <DropdownMenuItem onSelect={() => handleStatusChange(task.id, 'Completed')}>Completed</DropdownMenuItem>
                                            <DropdownMenuItem onSelect={() => handleStatusChange(task.id, 'Cancelled')}>Cancelled</DropdownMenuItem>
                                            <DropdownMenuItem onSelect={() => handleStatusChange(task.id, 'Rejected')}>Rejected</DropdownMenuItem>
                                        </>
                                    )}
                                </DropdownMenuContent>
                            </DropdownMenu>
                          </TableCell>
                          <TableCell>{task.description || '—'}</TableCell>
                          <TableCell className="text-right">
                             {canUpdate && (
                                 <Tooltip>
                                    <TooltipTrigger asChild>
                                        <Button variant="ghost" size="icon" onClick={() => handleOpenEditModal(task)} disabled={isTerminal}>
                                            <Edit className="h-4 w-4" />
                                        </Button>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                        <p>{isTerminal ? 'Task is locked' : 'Edit Task'}</p>
                                    </TooltipContent>
                                </Tooltip>
                             )}
                          </TableCell>
                        </TableRow>
                    );
                  })
                ) : (
                  <TableRow>
                    <TableCell colSpan={9} className="h-24 text-center">
                      No tasks created yet. Try the chatbot or the '+' button!
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>

      {canCreate && (
          <Button
            className="fixed bottom-8 left-1/2 -translate-x-1/2 z-50 h-14 w-14 rounded-full shadow-lg"
            onClick={handleOpenCreateModal}
          >
            <Plus className="h-6 w-6" />
            <span className="sr-only">Create Task Manually</span>
          </Button>
      )}

      <Modal open={isModalOpen} onClose={handleCloseModal}>
        <CreateTaskModal
          task={editingTask}
          onClose={handleCloseModal}
          onSave={handleSaveTask}
        />
      </Modal>
    </TooltipProvider>
  );
}
